apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: product-service
  labels:
    app: product-service
data:
  ##USER_SERVICE_URL: "http://user-service"
  USER_SERVICE_URL: "http://user-service.user-service.svc.cluster.local"

  DB_URL: "jdbc:postgresql://host.docker.internal:5433/productdb"

  DDL_AUTO: "validate"
  SHOW_SQL: "false"

  POOL_SIZE: "10"

  LOG_LEVEL: "INFO"
  SQL_LOG_LEVEL: "WARN"

  JAVA_OPTS: "-Xmx512m -Xms256m"
